#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(D: int, T: int, S: int) -> str:
def solve(D, T, S):
    return S * T >= D

# generated by online-judge-template-generator v4.4.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    D, T, S = map(int, input().split())
    a = solve(D, T, S)
    print(YES if a else NO)

if __name__ == '__main__':
    main()
