#!/usr/bin/env python3
# Generated by https://github.com/kyuridenamida/atcoder-tools
from typing import *
import itertools
import math
import sys

INF = float('inf')


def solve(R: int):
    return 2*R*math.pi


def main():

    sys.setrecursionlimit(10 ** 6)

    R = int(input())  # type: int
    print(solve(R))


if __name__ == '__main__':
    main()
