import sys
S=list(input())
A=int(S[0])
B=int(S[1])
C=int(S[2])
D=int(S[3])
if A+B+C+D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"+"+B+"+"+C+"+"+D+"=7")
  sys.exit()
elif A+B+C-D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"+"+B+"+"+C+"-"+D+"=7")
  sys.exit()
elif A+B-C+D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"+"+B+"-"+C+"+"+D+"=7")
  sys.exit()
elif A-B+C+D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"-"+B+"+"+C+"+"+D+"=7")
  sys.exit()
elif A+B-C-D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"+"+B+"-"+C+"-"+D+"=7")
  sys.exit()
elif A-B-C+D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"-"+B+"-"+C+"+"+D+"=7")
  sys.exit()
elif A-B+C-D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"-"+B+"+"+C+"-"+D+"=7")
  sys.exit()
elif A-B-C-D==7:
  A=str(A)
  B=str(B)
  C=str(C)
  D=str(D)
  print(A+"-"+B+"-"+C+"-"+D+"=7")
  sys.exit()