#!/usr/bin/env python3
import sys

MOD = 2  # type: int


def solve(N: int, P: int, A: "List[int]"):
    if not sum([e%2 for e in A]):
        if P:
            print(0)
        else:
            print(2**N)
    else:
      print(2**(N-1))
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, P, A)

if __name__ == '__main__':
    main()
