S = input()
T = ["AKIHABARA","KIHABARA","AKIHBARA","AKIHABRA","AKIHABAR"\
    ,"KIHBARA","KIHABRA","KIHABAR","AKIHBRA","AKIHBAR","AKIHABR"\
    ,"KIHBRA","KIHBAR","KIHABR","AKIHBR","KIHBR"]
print("YES" if S in T else "NO")