C = ['KIHBR','AKIHBR','AKIHABR','AKIHBAR','AKIHBRA','AKIHABAR','AKIHBARA','AKIHABARA',
    'KIHABR','KIHABAR','KIHABRA','KIHBAR','KIHBARA','KIHBRA','KIHABARA','AKHABRA']
print('YES' if input() in C else 'NO')