sx, sy, tx, ty = map(int,input().split())
dx = abs(sx-tx)
dy = abs(sy-ty)
print("U"*dy,end="")
print("R"*dx,end="")
print("D"*dy,end="")
print("L"*(dx+1),end="")
print("U"*(dy+1),end="")
print("R"*(dx+1),end="")
print("DR",end="")
print("D"*(dy+1),end="")
print("L"*(dx+1),end="")
print("U")