#!/usr/bin/env python3
import sys


def solve(X: int):
    target = 360
    count = 0
    while True:
        mod = target % X
        div = target // X
        count += div
        if mod == 0:
            break
        else:
            target = 360 + mod

    print(count)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
