#!/usr/bin/env python3
import sys


def solve(N: int, M: int):
    if M % 2 == 0:
        for m in range(1, M+1):
            if m % 2 == 1:
                k = (m+1) // 2
                print(k, M+1-k)
            elif m % 2 == 0:
                k = m // 2
                print(M+k, 2*M+2-k)
    if M % 2 == 1:
        for m in range(1, M+1):
            if m % 2 == 1:
                k = (m+1) // 2
                print(k, M+2-k)
            elif m % 2 == 0:
                k = m // 2
                print(M+1+k, 2*M+2-k)
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    solve(N, M)

if __name__ == '__main__':
    main()
