n,m = map(int,input().split())
lst0, lst1, lst2, lst3, lst4, lst5, lst6, lst7 =[],[],[],[],[],[],[],[]
for i in range(n):
    x,y,z = map(int,input().split())
    lst0.append(x+y+z)
    lst1.append(x+y-z)
    lst2.append(x-y+z)
    lst3.append(x-y-z)
    lst4.append(-x+y+z)
    lst5.append(-x+y-z)
    lst6.append(-x-y+z)
    lst7.append(-x-y-z)
lst0.sort(reverse=True)
lst1.sort(reverse=True)
lst2.sort(reverse=True)
lst3.sort(reverse=True)
lst4.sort(reverse=True)
lst5.sort(reverse=True)
lst6.sort(reverse=True)
lst7.sort(reverse=True)

res = []
res.append(sum(lst0[:m]))
res.append(sum(lst1[:m]))
res.append(sum(lst2[:m]))
res.append(sum(lst3[:m]))
res.append(sum(lst4[:m]))
res.append(sum(lst5[:m]))
res.append(sum(lst6[:m]))
res.append(sum(lst7[:m]))
print(max(res))